# Generated by Django 4.2.6 on 2023-11-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_registerdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdb',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='registerdb',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='registerdb',
            name='Mobile',
        ),
    ]
